<a href="https://colab.research.google.com/github/starsyntaxx/olist-data1/blob/main/notebooks/exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. upload the files

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving archive (1).zip to archive (1).zip

In [ ]:
import zipfile
import os

for file_name in uploaded.keys():
    if file_name.endswith(".zip"):
        with zipfile.ZipFile(file_name, 'r') as zip_ref:
            zip_ref.extractall("data")

Import tools.

In [ ]:
import pandas as pd

In [ ]:
os.listdir("data")

['olist_products_dataset.csv',
 'product_category_name_translation.csv',
 'olist_orders_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_customers_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_sellers_dataset.csv']

**Workflow 1: Analyze each dataset for signals before merging**

In [ ]:
products = pd.read_csv('data/olist_products_dataset.csv')
products.head(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

*Interacting with the product dataset.*

In [ ]:
products['product_category_name'].value_counts()

product_category_name
cama_mesa_banho                  3029
esporte_lazer                    2867
moveis_decoracao                 2657
beleza_saude                     2444
utilidades_domesticas            2335
                                 ...
fashion_roupa_infanto_juvenil       5
casa_conforto_2                     5
pc_gamer                            3
seguros_e_servicos                  2
cds_dvds_musicais                   1
Name: count, Length: 73, dtype: int64

In [ ]:
products.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [ ]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

question1: Are products with missing information sold

Analysis of the order Item dataset

In [ ]:
order_items = pd.read_csv('data/olist_order_items_dataset.csv')
order_items.head(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [ ]:
missing_products = products[products['product_category_name'].isnull()]
missing_products_ids = missing_products['product_id']
matched_orders = order_items[order_items['product_id'].isin(missing_products_ids)]

In [ ]:
matched_orders.head(20)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
123,0046e1d57f4c07c8c92ab26be8c3dfc0,1,ff6caf9340512b8bf6d2a2a6df032cfa,38e6dada03429a47197d5d584d793b41,2017-10-02 15:49:17,7.79,7.78
125,00482f2670787292280e0a8153d82467,1,a9c404971d1a5b1cbc2e4070e02731fd,702835e4b785b67a084280efca355756,2017-02-17 16:18:07,7.60,10.96
132,004f5d8f238e8908e6864b874eda3391,1,5a848e4ab52fd5445cdc07aab1c40e48,c826c40d7b19f62a09e2d7c5e7295ee2,2018-03-06 09:29:25,122.99,15.61
142,0057199db02d1a5ef41bacbf41f8f63b,1,41eee23c25f7a574dfaf8d5c151dbb12,e5a3438891c0bfdb9394643f95273d8e,2018-01-25 09:07:51,20.30,16.79
171,006cb7cafc99b29548d4f412c7f9f493,1,e10758160da97891c2fdcbc35f0f031d,323ce52b5b81df2cd804b017b7f09aa7,2018-02-22 13:35:28,56.00,14.14
370,00e6786fee8f476835c151a4d3fa9bf1,1,76d1a1a9d21ab677a61c3ae34b1b352f,c826c40d7b19f62a09e2d7c5e7295ee2,2018-03-15 01:31:04,159.77,16.00
378,00ed64bc080d87b4ab7f0c433bc5e98f,1,fbb1cfc2810efabf3235eccf4530f4ae,0c8380b62e38e8a1e6adbeba7eb9688c,2017-06-06 18:22:47,44.90,16.11
434,010a35dc7fc3808a03d243d2fd8c6e35,1,5a848e4ab52fd5445cdc07aab1c40e48,c826c40d7b19f62a09e2d7c5e7295ee2,2017-12-21 19:10:15,122.99,9.06
454,011080783e02d05b26c8c158b3653a42,1,9f69acd4da62618a3f6365b732d00ccd,897060da8b9a21f655304d50fd935913,2018-06-22 15:38:55,33.90,13.82
456,011108c8a3d6eee6807f48a2e639439f,1,ea11e700a343582ad56e4c70e966cb36,01cf7e3d21494c41fb86034f2e714fa1,2017-05-02 17:42:48,593.36,98.13
517,012f29911fcd2f1209d937741a6bbc6f,1,8c0bd0d6526379599b74a3a006d4c124,d66c305afaec317ebee552073a674429,2017-05-22 15:50:13,27.99,14.08
724,01b02139ac5f79a5de2c56284af7bb3e,1,76d1a1a9d21ab677a61c3ae34b1b352f,c826c40d7b19f62a09e2d7c5e7295ee2,2018-05-03 04:15:24,139.77,8.74
759,01be2f7ca246adb9112cb75096af2ee0,1,ad88641611c35ebd59ecda07a9f17099,c826c40d7b19f62a09e2d7c5e7295ee2,2018-02-16 18:08:13,157.77,14.85
803,01d72d42aaedb3736840132071d51100,1,8d39a63db6a98e40571f486e0c711cf7,c826c40d7b19f62a09e2d7c5e7295ee2,2018-03-26 12:56:36,147.20,18.91
834,01e7cf79ff6fdb0a65634f714c67dd24,1,32a99bb84ae79a55c0e446afc9310e1e,e5a3438891c0bfdb9394643f95273d8e,2018-02-21 14:10:35,27.30,11.85
887,020f8f4df303ae8aa39b806b766d2681,1,b1d207586fca400a2370d50a9ba1da98,1ca7077d890b907f89be8c954a02686a,2018-01-03 10:10:33,149.00,14.79
955,023ae47e11483bdb8aa35fa4662aee1c,1,00ab8a8b9fe219511dc3f178c6d79698,1b8356dabde1d35e17cef975c3f82730,2017-04-19 02:43:05,89.99,22.10
1196,02c8a77069dc7fd1cf273312c3a6e499,1,17823ffd2de8234f0e885a71109613a4,46dc3b2cc0980fb8ec44634e21d2718e,2017-09-06 00:05:03,279.99,15.55
1375,03343a88c4d669e6378c5aedc4147919,1,b36f3c918c91478c4559160022d3f14e,1ca7077d890b907f89be8c954a02686a,2018-01-22 12:16:58,150.00,8.30
1383,0339c36ce09427390de0dfe649d7e073,1,5a848e4ab52fd5445cdc07aab1c40e48,c826c40d7b19f62a09e2d7c5e7295ee2,2018-01-26 19:14:24,122.99,9.06

In [ ]:
matched_orders['product_id'].nunique()

610

In [ ]:
missing_products_ids.nunique()

610

Matched